version: "3"

services:

   etracs-server:
      volumes:
         - ./dev_modules/bpls:/services/modules/bpls
         - ./dev_modules/rules:/services/modules/rules
         - ./dev_modules/admin:/services/modules/admin
         - ./dev_modules/treasury:/services/modules/treasury
